=== nwillc/scotty/database.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://nwillc.github.io/scotty"
           xmlns:scotty="http://nwillc.github.io/scotty">
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="value" type="xs:string"/>
    <xs:element name="value" type="xs:string"/>

    <xs:element name="attribute">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="scotty:value" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="scotty:name" use="required"/>
            <xs:attribute ref="scotty:value" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="context">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="scotty:attribute"/>
                    <xs:element ref="scotty:context"/>
                    <xs:element ref="scotty:instance"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="instance">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="scotty:attribute"/>
                    <xs:element ref="scotty:context"/>
                    <xs:element ref="scotty:instance"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute ref="scotty:name" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="type">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="scotty:attribute"/>
                    <xs:element ref="scotty:context"/>
                    <xs:element ref="scotty:instance"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute ref="scotty:name" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== nwillc/scotty/examples/database/host.xml
<type name="host" xmlns="http://nwillc.github.io/scotty" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://nwillc.github.io/scotty http://nwillc.github.io/scotty/database.xsd">
    <context>
        <attribute name="env" value="dev"/>
        <instance>
            <attribute name="hostname" value="localhost"/>
            <attribute name="ip_address" value="127.0.0.1"/>
        </instance>
        <instance>
            <attribute name="hostname" value="devbox"/>
            <attribute name="ip_address" value="192.168.0.1"/>
        </instance>
    </context>
    <context>
        <attribute name="env" value="qa"/>
        <instance>
            <attribute name="hostname" value="qabox"/>
            <attribute name="ip_address" value="192.168.0.10"/>
        </instance>
    </context>
    <context>
        <attribute name="env" value="prod"/>
        <instance>
            <attribute name="hostname" value="prodbox1"/>
            <attribute name="ip_address" value="192.168.0.100"/>
        </instance>
        <instance>
            <attribute name="hostname" value="prodbox2"/>
            <attribute name="ip_address" value="192.168.0.101"/>
        </instance>
    </context>
</type>

=== nwillc/scotty/examples/database/user.xml
<type name="user" xmlns="http://nwillc.github.io/scotty" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://nwillc.github.io/scotty http://nwillc.github.io/scotty/database.xsd">

    <attribute name="username" value="guest"/>
    <attribute name="password" value="guestpw"/>

    <instance>
        <attribute name="env" value="prod"/>
        <instance>
            <attribute name="level" value="admin"/>
            <attribute name="username" value="admin"/>
            <attribute name="password" value="sekretz"/>
        </instance>
    </instance>
    <instance>
        <attribute name="env" value="qa"/>
        <instance>
            <attribute name="level" value="admin"/>
            <attribute name="username" value="qa"/>
            <attribute name="password" value="qapw"/>
        </instance>
    </instance>
</type>
